export const prizeData = [
  [
    "Free Entry to 4 individuals for all the technical symposiums organized by Phoenix Global, in India",
    "Workshops and Certification Courses (Finance, Analytics, Marketing, Operations, and Consulting) at a discounted price -->Phoenix Global",
    "4 vouchers for the courses offered by myways on their portal, 1 voucher per member",
    "4 codes for a year from Egghead, 1 code per member",
    "6 months free  1Password Family account for the winning team",
    "4 free ebooks, 1 to each member from Rosenfeld Media",
    "50% discount on selected courses of UAceIt ",
    "For each member  a year of Wolfram|One Personal Edition plus a one-year subscription to Wolfram|Alpha Pro",
    "Creation of Winner’s Spotlight Interview (to be scheduled within one month post-event) by Hackathons International ",
    "one Company Lifetime Package to the team from Clerky - (Worth $799)",
    "90% discount on courses from Coding Blocks",
    "1 t shirt to each member from GitHub",
  ],
  [
    "Workshops and Certification Courses (Finance, Analytics, Marketing, Operations, and Consulting) at a discounted price -->Phoenix Global",
    "4 vouchers for the courses offered by myways on their portal, 1 voucher per member",
    "4 codes for a year from Egghead, 1 code per member",
    "50% discount on selected courses of UAceIt",
    "For each member a year of Wolfram|One Personal Edition plus a one-year subscription to Wolfram|Alpha Pro.",
    "80% discount on courses from Coding Blocks",
    "1 t shirt to each member from GitHub",
  ],
  [
    "Workshops and Certification Courses (Finance, Analytics, Marketing, Operations, and Consulting) at a discounted price -->Phoenix Global",
    "4 vouchers for the courses offered by myways on their portal, 1 voucher per member",
    " 4 codes for a year from Egghead, 1 code per member",
    "50% discount on selected courses of UAceIt",
    "For each member a year of Wolfram|One Personal Edition plus a one-year subscription to Wolfram|Alpha Pro.",
    " 70 % discount on courses from Coding Blocks",
    "1 t shirt to each member from GitHub",
  ],
]
